M48
; DRILL file {KiCad (6.0.4)} date Tue Jun 28 09:06:21 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-28T09:06:21+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X105.76Y-67.815
X110.61Y-67.815
T2
X105.46Y-64.785
X110.91Y-64.785
T0
M30
